site_name: VOC framework
nav:
  - Framework API: index.md
  - Decisions: decisions.md
  - Validation: validation.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
